name: MortisMissions
version: '${project.version}'
main: com.mortisdevelopment.mortismissions.MortisMissions
api-version: 1.13
softdepend:
  - CrackShot
  - MythicMobs
  - QualityArmoryVehicles
  - WeaponMechanics
  - Brewery
commands:
  missions:
    aliases:
      - mission
      - mortismissions
      - mortismission
